name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.7.0+3
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  build: ^1.1.6
  source_gen: ^0.9.4+4
  hive: ">=1.3.0 <2.0.0"
  analyzer: ">=0.36.0 <0.40.0"
  dartx:
    git:
      url: https://github.com/yringler/dartx
      ref: update-path 

dev_dependencies:
  test: ^1.6.4
  build_test: any
  build_runner: any
  pedantic: "1.7.0"
